
FROM golang:1.24.4-bookworm@sha256:8faa537d0690017d8000e38e1ed9ed4c5990d40a3022ce2596a825c6c87f62c4 as build

# Set up build context
WORKDIR /build

# Accept GitHub token for private module access
ARG GITHUB_TOKEN
RUN git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
ENV GOPRIVATE=github.com/digicert/ctutils

# Copy only the main repo
COPY certificate-transparency-go/. ./certificate-transparency-go


# Change to the main Go module directory for dependency management
WORKDIR /build/certificate-transparency-go
RUN go mod tidy
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

# Build the server with optimizations
RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o ct_server ./trillian/ctfe/ct_server

RUN go mod download github.com/google/go-licenses/v2 && \
    go run github.com/google/go-licenses/v2 save ./trillian/ctfe/ct_server --save_path /THIRD_PARTY_NOTICES

FROM gcr.io/distroless/base-debian12@sha256:201ef9125ff3f55fda8e0697eff0b3ce9078366503ef066653635a3ac3ed9c26

COPY --from=build /build/certificate-transparency-go/ct_server /

ENTRYPOINT ["/ct_server"]
