FROM golang:1.24.4-bookworm@sha256:8faa537d0690017d8000e38e1ed9ed4c5990d40a3022ce2596a825c6c87f62c4 as build

WORKDIR /build

COPY . .

# Download all dependencies
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

RUN go build -mod=mod ./trillian/ctfe/ct_server

# Save licenses
RUN go run github.com/google/go-licenses/v2 save ./trillian/ctfe/ct_server --save_path /THIRD_PARTY_NOTICES

FROM gcr.io/distroless/base-debian12@sha256:201ef9125ff3f55fda8e0697eff0b3ce9078366503ef066653635a3ac3ed9c26

COPY --from=build /build/ct_server /
COPY --from=build /THIRD_PARTY_NOTICES /THIRD_PARTY_NOTICES

ENTRYPOINT ["/ct_server"]
